substitutions:
  nombre: "bano"
  friendly_name: "Mando WC"
  log_level: debug  
  stateTimerDelay: 30s  
    
 
  
packages:
  base:  !include wallswitchtypes/WallSwitchBase.yaml
  state_machine:  !include wallswitchtypes/TwoToggleStateMachine.yaml

 
  
  