esphome:
  name: calefaccion
  platform: ESP32
  board: az-delivery-devkit-v4
  
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "68a3e0d89fd0af957ed4d9c646dd2950"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password        


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Calefaccion Fallback Hotspot"
    password: "paMSeLjiZuP3"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  discovery: true

esp32_ble_tracker:
  scan_parameters:
    duration:  300s
    interval: 30011ms #512ms
    window: 30010ms #320m


sensor:
  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:2a:3d:03"
    temperature:
      name: "Sala Temperature"
    humidity:
      name: "Sala Humidity"
    battery_level:
      name: "Sala Battery-Level"

  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:2e:67:f0"
    temperature:
      name: "Estudio Temperature"
    humidity:
      name: "Estudio Humidity"
    battery_level:
      name: "Estudio Battery-Level"


  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:72:d7:97"
    temperature:
      name: "Baño Temperature"
    humidity:
      name: "Baño Humidity"
    battery_level:
      name: "Baño Battery-Level"

  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:cb:8a:18"
    temperature:
      name: "Ekain Temperature"
    humidity:
      name: "Ekain Humidity"
    battery_level:            

      name: "Ekain Battery-Level"


  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:d5:12:53"
    temperature:
      name: "Cocina Temperature"
    humidity:
      name: "Cocina Humidity"
    battery_level:
      name: "Cocina Battery-Level"

  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:d7:1f:5c"
    temperature:
      name: "Mia Temperature"
    humidity:
      name: "Mia Humidity"
    battery_level:
      name: "Mia Battery-Level"

  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:d9:1e:e3"
    temperature:
      name: "Irai Temperature"
    humidity:
      name: "Irai Humidity"
    battery_level:
      name: "Irai Battery-Level"
            

  - platform: template
    id: temperaturaActual
    name: "Temperatura Actual"
    
time:
  - platform: homeassistant
    id: esptime
    
output:
  - platform: template
    id: heater
    type: float
    write_action:
      - if:
          condition:
            lambda: return ((state > 0) && (state < .4));
          then:
            - delay: 500ms


    
switch:
  - platform: template
    name: "Caldera"
    id: heater2
    optimistic: true

climate:
  - platform: pid
    name: "PID Climate Controller"
    sensor: temperaturaActual
    default_target_temperature: 21°C
    heat_output: heater
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301
      
spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

font:
  - file: "fonts/Aadhunik.ttf"
    id: aadhunik
    size: 10

color:
  - id: my_red
    red: 100%
    green: 20%
    blue: 25%


display:
  - platform: ili9341
    model: TFT 2.4
    cs_pin: 14
    dc_pin: 27
    led_pin: 32  ### see note below ###
    reset_pin: 33

    lambda: |-
      it.fill(COLOR_BLACK);
      it.print(0, 0, id(aadhunik), id(my_red), TextAlign::TOP_LEFT, "Hello World!");