substitutions:
  nombre: "mia"
  friendly_name: "Mando Mia"
  log_level: debug
  stateTimerDelay: 30s
  left_pin_number: GPIO19
  right_pin_number: GPIO18

 
packages:
  base:  !include wallswitchtypes/WallSwitchBase.yaml
  state_machine:  !include wallswitchtypes/TwoToggleTwoBlindStateMachine.yaml
 
 
   