substitutions:
  nombre: "sala"
  friendly_name: "Mando Sala"
  log_level: debug  
  stateTimerDelay: 30s  
  left_pin_number: GPIO32
  right_pin_number: GPIO33
  
 
  
packages:
  base:  !include wallswitchtypes/WallSwitchBase.yaml
  state_machine:  !include wallswitchtypes/TwoToggleOneBlindStateMachine.yaml

 
  