esphome:
  name: termometro
  platform: ESP32
  board: az-delivery-devkit-v4


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "bb74fc7f7b636cd674b7f16da52728ff"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "5AVlHWgbQFfN"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  discovery: true

esp32_ble_tracker:
  scan_parameters:
    duration:  300s
    interval: 30011ms #512ms
    window: 30010ms #320m


sensor:
  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:2a:3d:03"
    temperature:
      name: "Sala Temperature"
    humidity:
      name: "Sala Humidity"
    battery_level:
      name: "Sala Battery-Level"

  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:2e:67:f0"
    temperature:
      name: "Estudio Temperature"
    humidity:
      name: "Estudio Humidity"
    battery_level:
      name: "Estudio Battery-Level"


  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:72:d7:97"
    temperature:
      name: "Baño Temperature"
    humidity:
      name: "Baño Humidity"
    battery_level:
      name: "Baño Battery-Level"

  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:cb:8a:18"
    temperature:
      name: "Ekain Temperature"
    humidity:
      name: "Ekain Humidity"
    battery_level:
      name: "Ekain Battery-Level"


  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:d5:12:53"
    temperature:
      name: "Cocina Temperature"
    humidity:
      name: "Cocina Humidity"
    battery_level:
      name: "Cocina Battery-Level"

  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:d7:1f:5c"
    temperature:
      name: "Mia Temperature"
    humidity:
      name: "Mia Humidity"
    battery_level:
      name: "Mia Battery-Level"

  - platform: pvvx_mithermometer
    mac_address: "a4:c1:38:d9:1e:e3"
    temperature:
      name: "Irai Temperature"
    humidity:
      name: "Irai Humidity"
    battery_level:
      name: "Irai Battery-Level"
      
number:
  - platform: template
    name: Current
    id: mysensor
    state_topic: casa/calefaccion/current
    optimistic: true
    min_value: 0
    max_value: 100
    step: 0.01
    
i2c:
  sda: GPIO21
  scl: GPIO22

font:
  - file: "fonts/Aadhunik.ttf"
    id: my_font20
    size: 10
    

output:
  - id: generic_out
    platform: gpio
    pin: GPIO16


display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 10, id(my_font20), "Irai Forero Irazola");
      // Draw a line from [0,0] to [100,50]
      //it.line(0, 0, 100, 50);
      // Draw the outline of a rectangle with the top left at [50,60], a width of 30 and a height of 42
      //it.rectangle(50, 60, 30, 42);
      // Draw the same rectangle, but this time filled.
      //it.filled_rectangle(0, 0, 127, 63);

      // Circles! Let's draw one with the center at [25,25] and a radius of 10
      //it.circle(25, 25, 10);
      // ... and the same thing filled again
      //it.filled_circle(25, 25, 10);
