esphome:
  name: test
  includes:
    - custom/sse/sse.h
    - custom/sh2lib/sh2lib.h
    - custom/sh2lib/sh2lib.c
#  platform: ESP32
#  board: az-delivery-devkit-v4

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP_TLS_INSECURE: y
      CONFIG_ESP_TLS_SKIP_SERVER_CERT_VERIFY: y

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "eca277f984e48e65cc768b41505d14ef"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "6GyJ8F00gvtt"



sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new SSE();
    App.register_component(my_sensor);
    return {my_sensor};

  sensors:
    name: "My Custom Sensor"