esphome:
  name: tft
  platform: ESP32
  board: az-delivery-devkit-v4

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


font:
  - file: "fonts/Aadhunik.ttf"
    id: aadhunik
    size: 40

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
    
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%


spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19
  
  
xpt2046:
  id: touchscreen
  cs_pin: 32
  irq_pin: 4
  update_interval: 50ms
  report_interval: 1s
  threshold: 400
  dimension_x: 240
  dimension_y: 320
  calibration_x_min: 3860
  calibration_x_max: 280
  calibration_y_min: 340
  calibration_y_max: 3860
  swap_x_y: false

binary_sensor:
  - platform: xpt2046
    xpt2046_id: touchscreen
    id: touch_key0
    x_min: 80
    x_max: 160
    y_min: 106
    y_max: 212
    on_state:
      - lambda: 'ESP_LOGI("main", "key0: %s", (x ? "touch" : "release"));'  
      
text_sensor:
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: mysensor
    topic: casa/calefaccion/temperaturaactual


switch:
  - platform: template
    name: "Template Switch"
    optimistic: true
    lambda: |-
      if (id(touch_key0).state) {
        return true;
      } else {
        return false;
      }


display:
  - platform: ili9341
    model: TFT 2.4
    cs_pin: 5
    dc_pin: 26
    led_pin: 33  ### see note below ###
    reset_pin: 27
    rotation: 270
    lambda: |-
      it.fill(COLOR_BLACK);
      // it.print(40, 30, id(aadhunik), id(my_red), TextAlign::TOP_LEFT, "By Forero");
      it.filled_rectangle(80, 80, 106, 106, id(my_green));
      it.printf(0, 0, id(aadhunik), "The data is: %s", id(mysensor).state.c_str());


mqtt:
  broker: !secret mqtt_broker
  discovery: true
  on_json_message:
    topic: casa/calefaccion
    then:


#esp32_ble_tracker:
#  scan_parameters:
#    duration:  300s
#    interval: 1s #512ms
#    window: 500ms #320m
#    active: false



            


    
