  # https://erikflowers.github.io/weather-icons/
  - file: "fonts/weathericons-regular-webfont.ttf"
    id: fontClima
    size: 50
    glyphs: [
      # Daytime
      # "", # (f00d) wi-day-sunny 
      # "", # (f002) wi-day-cloudy 
      # "", # (f000) wi-day-cloudy-gusts 
      # "", # (f001) wi-day-cloudy-windy 
      # "", # (f003) wi-day-fog 
      # "", # (f004) wi-day-hail 
      # "", # (f0b6) wi-day-haze 
      # "", # (f005) wi-day-lightning 
      # "", # (f008) wi-day-rain 
      # "", # (f006) wi-day-rain-mix 
      # "", # (f007) wi-day-rain-wind 
      # "", # (f009) wi-day-showers 
      # "", # (f0b2) wi-day-sleet 
      # "", # (f068) wi-day-sleet-storm 
      # "", # (f00a) wi-day-snow 
      # "", # (f06b) wi-day-snow-thunderstorm 
      # "", # (f065) wi-day-snow-wind 
      # "", # (f00b) wi-day-sprinkle 
      # "", # (f00e) wi-day-storm-showers 
      # "", # (f00c) wi-day-sunny-overcast 
      # "", # (f010) wi-day-thunderstorm 
      # "", # (f085) wi-day-windy 
      # "", # (f06e) wi-solar-eclipse 
      # "", # (f072) wi-hot 
      # "", # (f07d) wi-day-cloudy-high 
      # "", # (f0c4) wi-day-light-wind 
      # Nighttime
      # "", # (f02e) wi-night-clear 
      # "", # (f086) wi-night-alt-cloudy 
      # "", # (f022) wi-night-alt-cloudy-gusts 
      # "", # (f023) wi-night-alt-cloudy-windy 
      # "", # (f024) wi-night-alt-hail 
      # "", # (f025) wi-night-alt-lightning 
      # "", # (f028) wi-night-alt-rain 
      # "", # (f026) wi-night-alt-rain-mix 
      # "", # (f027) wi-night-alt-rain-wind 
      # "", # (f029) wi-night-alt-showers 
      # "", # (f0b4) wi-night-alt-sleet 
      # "", # (f06a) wi-night-alt-sleet-storm 
      # "", # (f02a) wi-night-alt-snow 
      # "", # (f06d) wi-night-alt-snow-thunderstorm 
      # "", # (f067) wi-night-alt-snow-wind 
      # "", # (f02b) wi-night-alt-sprinkle 
      # "", # (f02c) wi-night-alt-storm-showers 
      # "", # (f02d) wi-night-alt-thunderstorm 
      # "", # (f031) wi-night-cloudy 
      # "", # (f02f) wi-night-cloudy-gusts 
      # "", # (f030) wi-night-cloudy-windy 
      # "", # (f04a) wi-night-fog 
      # "", # (f032) wi-night-hail 
      # "", # (f033) wi-night-lightning 
      # "", # (f083) wi-night-partly-cloudy 
      # "", # (f036) wi-night-rain 
      # "", # (f034) wi-night-rain-mix 
      # "", # (f035) wi-night-rain-wind 
      # "", # (f037) wi-night-showers        
      # "", # (f0b3) wi-night-sleet 
      # "", # (f069) wi-night-sleet-storm 
      # "", # (f038) wi-night-snow 
      # "", # (f06c) wi-night-snow-thunderstorm 
      # "", # (f066) wi-night-snow-wind 
      # "", # (f039) wi-night-sprinkle 
      # "", # (f03a) wi-night-storm-showers 
      # "", # (f03b) wi-night-thunderstorm 
      # "", # (f070) wi-lunar-eclipse 
      # "", # (f077) wi-stars 
      # "", # (f01d) wi-storm-showers 
      # "", # (f07e) wi-night-alt-cloudy-high 
      # "", # (f080) wi-night-cloudy-high 
      # "", # (f081) wi-night-alt-partly-cloudy 
      # Neutral
      # "", # (f041) wi-cloud 
      # "", # (f013) wi-cloudy 
      # "", # (f011) wi-cloudy-gusts 
      # "", # (f012) wi-cloudy-windy 
      # "", # (f014) wi-fog 
      # "", # (f015) wi-hail 
      # "", # (f019) wi-rain 
      # "", # (f017) wi-rain-mix A
      # "", # (f018) wi-rain-wind 
      # "", # (f01a) wi-showers 
      # "", # (f0b5) wi-sleet 
      # "", # (f01b) wi-snow 
      # "", # (f01c) wi-sprinkle 
      # "", # (f01e) wi-thunderstorm 
      # "", # (f064) wi-snow-wind 
      # "", # (f074) wi-smog 
      # "", # (f062) wi-smoke 
      # "", # (f016) wi-lightning 
      # "", # (f04e) wi-raindrops 
      # "", # (f078) wi-raindrop 
      # "", # (f063) wi-dust 
      # "", # (f076) wi-snowflake-cold 
      # "", # (f021) wi-windy 
      # "", # (f050) wi-strong-wind 
      # "", # (f082) wi-sandstorm 
      # "", # (f0c6) wi-earthquake 
      # "", # (f0c7) wi-fire 
      # "", # (f07c) wi-flood 
      # "", # (f071) wi-meteor 
      # "", # (f0c5) wi-tsunami 
      # "", # (f0c8) wi-volcano 
      # "", # (f073) wi-hurricane 
      # "", # (f056) wi-tornado 
      # "", # (f0cc) wi-small-craft-advisory 
      # "", # (f0cd) wi-gale-warning 
      # "", # (f0ce) wi-storm-warning 
      # "", # (f0cf) wi-hurricane-warning 
      # "", # (f0b1) wi-wind-direction 
      # Miscellaneous
      # "", # (f075) wi-alien 
      # "", # (f03c) wi-celsius 
      # "", # (f045) wi-fahrenheit 
      # "", # (f042) wi-degrees 
      # "", # (f055) wi-thermometer 
      # "", # (f053) wi-thermometer-exterior 
      # "", # (f054) wi-thermometer-internal 
      # "", # (f03d) wi-cloud-down 
      # "", # (f040) wi-cloud-up 
      # "", # (f03e) wi-cloud-refresh 
      # "", # (f047) wi-horizon 
      # "", # (f046) wi-horizon-alt 
      # "", # (f051) wi-sunrise 
      # "", # (f052) wi-sunset 
      # "", # (f0c9) wi-moonrise 
      # "", # (f0ca) wi-moonset 
      # "", # (f04c) wi-refresh 
      # "", # (f04b) wi-refresh-alt 
      # "", # (f084) wi-umbrella 
      # "", # (f079) wi-barometer 
      # "", # (f07a) wi-humidity 
      # "", # (f07b) wi-na 
      # "", # (f0cb) wi-train 
      # Moon Phases
      # "", # (f095) wi-moon-new 
      # "", # (f096) wi-moon-waxing-crescent-1 
      # "", # (f097) wi-moon-waxing-crescent-2 
      # "", # (f098) wi-moon-waxing-crescent-3 
      # "", # (f099) wi-moon-waxing-crescent-4 
      # "", # (f09a) wi-moon-waxing-crescent-5 
      # "", # (f09b) wi-moon-waxing-crescent-6 
      # "", # (f09c) wi-moon-first-quarter 
      # "", # (f09d) wi-moon-waxing-gibbous-1 
      # "", # (f09e) wi-moon-waxing-gibbous-2 
      # "", # (f09f) wi-moon-waxing-gibbous-3 
      # "", # (f0a0) wi-moon-waxing-gibbous-4 
      # "", # (f0a1) wi-moon-waxing-gibbous-5 
      # "", # (f0a2) wi-moon-waxing-gibbous-6 
      # "", # (f0a3) wi-moon-full 
      # "", # (f0a4) wi-moon-waning-gibbous-1 
      # "", # (f0a5) wi-moon-waning-gibbous-2 
      # "", # (f0a6) wi-moon-waning-gibbous-3 
      # "", # (f0a7) wi-moon-waning-gibbous-4 
      # "", # (f0a8) wi-moon-waning-gibbous-5 
      # "", # (f0a9) wi-moon-waning-gibbous-6 
      # "", # (f0aa) wi-moon-third-quarter 
      # "", # (f0ab) wi-moon-waning-crescent-1 
      # "", # (f0ac) wi-moon-waning-crescent-2 
      # "", # (f0ad) wi-moon-waning-crescent-3 
      # "", # (f0ae) wi      # "-moon-waning-crescent-4 
      # "", # (f0af) wi-moon-waning-crescent-5 
      # "", # (f0b0) wi-moon-waning-crescent-6 
      # "", # (f0eb) wi-moon-alt-new 
      # "", # (f0d0) wi-moon-alt-waxing-crescent-1 
      # "", # (f0d1) wi-moon-alt-waxing-crescent-2 
      # "", # (f0d2) wi-moon-alt-waxing-crescent-3 
      # "", # (f0d3) wi-moon-alt-waxing-crescent-4 
      # "", # (f0d4) wi-moon-alt-waxing-crescent-5 
      # "", # (f0d5) wi-moon-alt-waxing-crescent-6 
      # "", # (f0d6) wi-moon-alt-first-quarter 
      # "", # (f0d7) wi-moon-alt-waxing-gibbous-1 
      # "", # (f0d8) wi-moon-alt-waxing-gibbous-2 
      # "", # (f0d9) wi-moon-alt-waxing-gibbous-3 
      # "", # (f0da) wi-moon-alt-waxing-gibbous-4 
      # "", # (f0db) wi-moon-alt-waxing-gibbous-5 
      # "", # (f0dc) wi-moon-alt-waxing-gibbous-6 
      # "", # (f0dd) wi-moon-alt-full 
      # "", # (f0de) wi-moon-alt-waning-gibbous-1 
      # "", # (f0df) wi-moon-alt-waning-gibbous-2 
      # "", # (f0e0) wi-moon-alt-waning-gibbous-3 
      # "", # (f0e1) wi-moon-alt-waning-gibbous-4 
      # "", # (f0e2) wi-moon-alt-waning-gibbous-5 
      # "", # (f0e3) wi-moon-alt-waning-gibbous-6 
      # "", # (f0e4) wi-moon-alt-third-quarter 
      # "", # (f0e5) wi-moon-alt-waning-crescent-1 
      # "", # (f0e6) wi-moon-alt-waning-crescent-2 
      # "", # (f0e7) wi-moon-alt-waning-crescent-3 
      # "", # (f0e8) wi-moon-alt-waning-crescent-4 
      # "", # (f0e9) wi-moon-alt-waning-crescent-5 
      # "", # (f0ea) wi-moon-alt-waning-crescent-6 
      # Time
      # "", # (f08a) wi-time-1 
      # "", # (f08b) wi-time-2 
      # "", # (f08c) wi-time-3 
      # "", # (f08d) wi-time-4 
      # "", # (f08e) wi-time-5 
      # "", # (f08f) wi-time-6 
      # "", # (f090) wi-time-7 
      # "", # (f091) wi-time-8 
      # "", # (f092) wi-time-9 
      # "", # (f093) wi-time-10 
      # "", # (f094) wi-time-11 
      # "", # (f089) wi-time-12 
      # Directional Arrows
      # "", # (f058) wi-direction-up 
      # "", # (f057) wi-direction-up-right 
      # "", # (f04d) wi-direction-right 
      # "", # (f088) wi-direction-down-right 
      # "", # (f044) wi-direction-down 
      # "", # (f043) wi-direction-down-left 
      # "", # (f048) wi-direction-left 
      # "" # (f087) wi-direction-up-left
    ]